language: node_js
node_js:
  - stable
  
cache:
  directories:
  - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
before_script:
  - yarn add gatsby-cli
script:
  - yarn run test
after_success:
  - echo "berghall.dev" > ./public/CNAME
  - yarn run deploy